<a href="https://colab.research.google.com/github/sagarkakde8329/DataScience-SE22/blob/main/Experiment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


determinant = np.linalg.det(matrix)


In [2]:
print("The 3x3 matrix is:")
print(matrix)
print(f"\nThe determinant of the matrix is: {determinant}")


The 3x3 matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The determinant of the matrix is: 0.0
