<a href="https://colab.research.google.com/github/sagarkakde8329/DataScience-SE22/blob/main/Experiment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


determinant = np.linalg.det(matrix)


In [2]:
print("The 3x3 matrix is:")
print(matrix)
print(f"\nThe determinant of the matrix is: {determinant}")


The 3x3 matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The determinant of the matrix is: 0.0


In [5]:
import numpy as np


new_matrix = np.array([
    [1, 2, 0],
    [0, 1, 0],
    [0, 0, 1]
])


new_determinant = np.linalg.det(new_matrix)

inverse_matrix = np.linalg.inv(new_matrix)


In [6]:
print("The new non-singular 3x3 matrix is:")
print(new_matrix)
print(f"\nThe determinant of the new matrix is: {new_determinant}")
print(f"\nThe inverse of the new matrix is:\n{inverse_matrix}")


The new non-singular 3x3 matrix is:
[[1 2 0]
 [0 1 0]
 [0 0 1]]

The determinant of the new matrix is: 1.0

The inverse of the new matrix is:
[[ 1. -2.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constant vector B
B = np.array([10, 20])

# Solve the system of linear equations Ax = B
solution = np.linalg.solve(A, B)

x_value = solution[0]
y_value = solution[1]


In [8]:
print("The system of linear equations is:")
print("2x + 3y = 10")
print("4x + 5y = 20")
print(f"\nThe solution is: x = {x_value}, y = {y_value}")


The system of linear equations is:
2x + 3y = 10
4x + 5y = 20

The solution is: x = 5.0, y = 0.0
